spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/wvpfaqvh?createDatabaseIfNotExist=true&useSSL=true
    username: wvpfaqvh
    password: X6fd530rtO-FwB1pY52v5rvJaHnjx2Or
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql

