server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/v1/api/users/**
        - id: book-service
          uri: http://localhost:8082
          predicates:
            - Path=/v1/api/books/**
        - id: category-service
          uri: http://localhost:8082
          predicates:
            - Path=/v1/api/categories/**
        - id: purchase-service
          uri: http://localhost:8081
          predicates:
            - Path=/v1/api/purchases/**
